version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # POSTGRES_DB: django-backend-db
      # POSTGRES_USER: django-backend-admin
      # POSTGRES_PASSWORD: uu*ii*dd1234

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      # PGADMIN_DEFAULT_EMAIL: user@domain.com
      # PGADMIN_DEFAULT_PASSWORD: SuperSecret
    ports:
      - 5050:80